/*
 * export_model.c — convert a Sentinel quantized checkpoint (SLMQ format, from
 * the core's `--quantize` / `--quantize-train`) into a model.h of flat
 * quantized arrays for the ESP32 firmware's inference.h.
 *
 * Build & run on a PC (NOT the ESP32):
 *     cc -O2 -o export_model export_model.c
 *     ./export_model sentinel-1bit-qat.bin model.h      # or sentinel-int8-qat.bin
 *
 * It preserves the quantization (int8 or 1-bit) exactly — no re-quantizing —
 * so the model that ran well under QAT on the PC runs identically on-device.
 * model.h holds the weights as `const` (flash .rodata), costing no RAM.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define QUANT_MAGIC 0x534C4D51u   /* "SLMQ" — must match the core */

static size_t rowbytes(int cols, int qmode) {
    return (qmode == 8) ? (size_t)cols : (size_t)((cols + 7) / 8);
}

/* read `rows` quantized rows (each: float scale/alpha + packed bytes) */
static int read_tensor(FILE *f, int rows, int cols, int qmode,
                       unsigned char *data, float *scale) {
    size_t rb = rowbytes(cols, qmode);
    for (int i = 0; i < rows; i++) {
        if (fread(&scale[i], sizeof(float), 1, f) != 1) return 0;
        if (fread(data + (size_t)i * rb, 1, rb, f) != rb) return 0;
    }
    return 1;
}

static void emit_packed(FILE *o, const char *name, int qmode,
                        const unsigned char *d, size_t n) {
    fprintf(o, "static const %s %s[%zu] = {\n",
            qmode == 8 ? "int8_t" : "uint8_t", name, n);
    for (size_t k = 0; k < n; k++) {
        if (qmode == 8) fprintf(o, "%d,", (int)(signed char)d[k]);
        else            fprintf(o, "%u,", (unsigned)d[k]);
        if ((k & 31) == 31) fputc('\n', o);
    }
    fprintf(o, "\n};\n");
}

static void emit_floats(FILE *o, const char *name, const float *d, size_t n) {
    fprintf(o, "static const float %s[%zu] = {\n", name, n);
    for (size_t k = 0; k < n; k++) {
        fprintf(o, "%.8ef,", d[k]);
        if ((k & 7) == 7) fputc('\n', o);
    }
    fprintf(o, "\n};\n");
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s <quantized.bin> [model.h]\n", argv[0]); return 1; }
    const char *inp = argv[1];
    const char *outp = (argc >= 3) ? argv[2] : "model.h";

    FILE *f = fopen(inp, "rb");
    if (!f) { perror("open input"); return 1; }
    unsigned hdr[7];
    if (fread(hdr, sizeof(unsigned), 7, f) != 7 || hdr[0] != QUANT_MAGIC) {
        fprintf(stderr, "not a Sentinel quantized (SLMQ) file\n"); fclose(f); return 1;
    }
    int qmode = (int)hdr[1], V = (int)hdr[2], E = (int)hdr[3], H = (int)hdr[4], L = (int)hdr[5];
    int G = 3;
    size_t rbH = rowbytes(H, qmode), rbE = rowbytes(E, qmode);

    /* allocate flat buffers */
    unsigned char *WembD = malloc((size_t)V * rbE);
    float         *WembS = malloc((size_t)V * sizeof(float));
    unsigned char *WgD   = malloc((size_t)L * G * H * rbH);
    float         *WgS   = malloc((size_t)L * G * H * sizeof(float));
    unsigned char *UgD   = malloc((size_t)L * G * H * rbH);
    float         *UgS   = malloc((size_t)L * G * H * sizeof(float));
    unsigned char *WhyD  = malloc((size_t)V * rbH);
    float         *WhyS  = malloc((size_t)V * sizeof(float));
    float         *bg    = malloc((size_t)L * G * H * sizeof(float));
    float         *by    = malloc((size_t)V * sizeof(float));
    if (!WembD||!WembS||!WgD||!WgS||!UgD||!UgS||!WhyD||!WhyS||!bg||!by) {
        fprintf(stderr, "out of memory\n"); return 1; }

    int ok = 1;
    ok &= read_tensor(f, V, E, qmode, WembD, WembS);
    for (int l = 0; l < L && ok; l++)
        for (int g = 0; g < G && ok; g++) {
            int gi = l * G + g;
            ok &= read_tensor(f, H, H, qmode, WgD + (size_t)gi * H * rbH, WgS + (size_t)gi * H);
            ok &= read_tensor(f, H, H, qmode, UgD + (size_t)gi * H * rbH, UgS + (size_t)gi * H);
        }
    ok &= read_tensor(f, V, H, qmode, WhyD, WhyS);
    ok &= (fread(bg, sizeof(float), (size_t)L * G * H, f) == (size_t)L * G * H);
    ok &= (fread(by, sizeof(float), (size_t)V, f) == (size_t)V);
    fclose(f);
    if (!ok) { fprintf(stderr, "truncated or malformed checkpoint\n"); return 1; }

    FILE *o = fopen(outp, "w");
    if (!o) { perror("open output"); return 1; }
    fprintf(o, "/* auto-generated by export_model.c from %s — do not edit */\n", inp);
    fprintf(o, "#ifndef SENTINEL_MODEL_H\n#define SENTINEL_MODEL_H\n#include <stdint.h>\n");
    fprintf(o, "#define SM_VOCAB %d\n#define SM_EMBED %d\n#define SM_HIDDEN %d\n", V, E, H);
    fprintf(o, "#define SM_LAYERS %d\n#define SM_QMODE %d\n", L, qmode);
    fprintf(o, "enum { GZ=0, GR=1, GN=2 };\n");

    const char *qs = (qmode == 8) ? "q" : "b";   /* data suffix */
    const char *ss = (qmode == 8) ? "s" : "a";   /* scale suffix */
    char nm[32];
    snprintf(nm, sizeof nm, "SM_Wemb_%s", qs); emit_packed(o, nm, qmode, WembD, (size_t)V * rbE);
    snprintf(nm, sizeof nm, "SM_Wemb_%s", ss); emit_floats(o, nm, WembS, (size_t)V);
    snprintf(nm, sizeof nm, "SM_Wg_%s", qs);   emit_packed(o, nm, qmode, WgD, (size_t)L*G*H*rbH);
    snprintf(nm, sizeof nm, "SM_Wg_%s", ss);   emit_floats(o, nm, WgS, (size_t)L*G*H);
    snprintf(nm, sizeof nm, "SM_Ug_%s", qs);   emit_packed(o, nm, qmode, UgD, (size_t)L*G*H*rbH);
    snprintf(nm, sizeof nm, "SM_Ug_%s", ss);   emit_floats(o, nm, UgS, (size_t)L*G*H);
    snprintf(nm, sizeof nm, "SM_Why_%s", qs);  emit_packed(o, nm, qmode, WhyD, (size_t)V*rbH);
    snprintf(nm, sizeof nm, "SM_Why_%s", ss);  emit_floats(o, nm, WhyS, (size_t)V);
    emit_floats(o, "SM_bg", bg, (size_t)L*G*H);
    emit_floats(o, "SM_by", by, (size_t)V);
    fprintf(o, "#endif /* SENTINEL_MODEL_H */\n");
    fclose(o);

    long wbytes = (long)(V*rbE + 2L*L*G*H*rbH + V*rbH);
    printf("wrote %s  (V=%d E=%d H=%d L=%d, %s, ~%ld bytes of weights in flash)\n",
           outp, V, E, H, L, qmode == 8 ? "int8" : "1-bit", wbytes);
    return 0;
}
